name: final_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  intl: ^0.19.0
  image_picker: ^1.1.2
  firebase_storage: ^12.0.1
  url_launcher: ^6.3.0
  firebase_app_check: ^0.3.0+1
  curved_navigation_bar: ^1.0.3
  cached_network_image: ^3.3.1
  random_string: ^2.3.1
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0

  # Added for Map Feature
  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0
  google_maps_cluster_manager_2: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - Images/
    - Images/map_style.json
    - Images/map_style_dark.json
