name: final_project
description: "A new University event Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  image_picker: ^1.1.2
  random_string: ^2.3.1
  cupertino_icons: ^1.0.8
  firebase_app_check: ^0.2.2+1
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.4.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.2.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - Images/

flutter_native_splash:
  image: Images/onboarding.png
  color: "#00008B"
  android_gravity: center
  ios_content_mode: center

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Images/Logo.png"
