name: final_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  google_sign_in: ^6.2.1
  google_nav_bar: ^5.0.6
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  firebase_storage: ^12.1.0
  geolocator: ^12.0.0
  google_maps_flutter: ^2.7.0
  intl: ^0.19.0
  flutter_polyline_points: ^2.0.0
  cached_network_image: ^3.3.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1
  curved_navigation_bar: ^1.0.6
  firebase_app_check: ^0.3.1
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.3.2
  google_maps_cluster_manager_2: ^3.2.0
  in_app_review: ^2.0.11
  nested: ^1.0.0
  provider: ^6.1.5+1
  random_string: ^2.3.1
  share_plus: ^9.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  flutter_image_compress: ^2.3.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - Images/
